M48
; DRILL file KiCad 10.0.3 date 2026-06-05T10:06:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-05T10:06:55+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X68.6Y-70.8
X68.6Y-94.6
X91.9Y-70.8
X91.9Y-94.6
T2
X52.35Y-82.7
X108.15Y-82.7
M30
